ex: dup ( x -- x x ) [x | rest] = stack; [x, x | rest] ex;
ex: drop ( x -- ) [_ | rest] = stack; rest ex;
ex: swap ( a b -- b a ) [a, b | rest] = stack; [b, a | rest] ex;
ex: over ( a b -- a b a ) [a, b | rest] = stack; [b, a, b | rest] ex;
ex: < ( a b -- bool ) [b, a | rest] = stack; [a < b | rest] ex;
ex: > ( a b -- bool ) [b, a | rest] = stack; [a > b | rest] ex;
ex: = ( a b -- bool ) [b, a | rest] = stack; [a == b | rest] ex;
ex: negate ( n -- n ) [n | rest] = stack; [-n | rest] ex;
ex: <= ( a b -- bool ) [b, a | rest] = stack; [a <= b | rest] ex;
ex: . ( x -- ) [x | rest] = stack; IO.puts(x); rest ex;
ex: puts ( x -- ) [x | rest] = stack; IO.puts(x); rest ex;
